/** Credentials stay in memory; all user/provider strings render through textContent. */
export const consoleHtml = `<!doctype html><html lang="de"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Social Media OS</title><link rel="stylesheet" href="/console.css">
<header><p class="eyebrow">SOCIAL MEDIA OS</p><h1>Eine Marke. Ein klarer Kontext.</h1><p>Entwürfe prüfen und vorbereiten. Veröffentlichung und Terminierung sind gesperrt.</p></header>
<section class="access"><label>Zugangstoken <input id="token" type="password" autocomplete="off"></label><button id="login">Verbinden</button><button id="logout">Abmelden</button></section>
<section class="switch"><label>Marke und Kanal <select id="workspace" disabled></select></label></section><p id="message" role="status"></p>
<main id="content"></main><script src="/console.js" defer></script></html>`;
export const consoleCss = `
:root{font-family:system-ui,sans-serif;color:#132c32;background:#f3f5ef;line-height:1.6}body{max-width:1050px;margin:auto;padding:32px}header{border-bottom:2px solid #183a3e;margin-bottom:24px;padding-bottom:24px}h1{font-size:clamp(28px,5vw,46px);line-height:1.1;letter-spacing:-1px}h2{font-size:26px}h3{margin-top:0}.eyebrow{font-size:12px;letter-spacing:3px}section,article{background:white;padding:24px;border:1px solid #d5ddd4;border-radius:12px;margin:18px 0}.access{display:flex;flex-wrap:wrap;align-items:end;gap:12px}.access label{flex:1}.switch{background:#e1eadf}label{display:block;font-size:14px;font-weight:600;margin:12px 0}input,textarea,select{box-sizing:border-box;width:100%;border:1px solid #9aaea7;border-radius:6px;padding:10px;font:inherit;background:#fff;color:inherit}textarea{min-height:90px;resize:vertical}button{font:inherit;border:0;border-radius:6px;padding:10px 16px;margin:6px 8px 0 0;background:#164f4a;color:white;cursor:pointer}button:disabled{opacity:.5;cursor:wait}#logout{background:#e8ede8;color:#163c36}#message{color:#9b3524;white-space:pre-wrap}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit}.muted{color:#526a66;font-size:14px}table{width:100%;border-collapse:collapse}td,th{text-align:left;border-bottom:1px solid #ddd;padding:8px}.caption{white-space:pre-wrap}a{color:#164f4a}button:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible{outline:3px solid #b2772c;outline-offset:2px}
`;
export const consoleScript = String.raw`
const $=id=>document.getElementById(id);let token='',epoch=0;
function node(tag,text,cls){const el=document.createElement(tag);el.textContent=text;if(cls)el.className=cls;return el;}
function clear(){epoch++;$('content').replaceChildren();$('message').textContent='';}
async function api(path,data,workspace){const response=await fetch(path,{method:data?'POST':'GET',headers:{Authorization:'Bearer '+token,...(data?{'Content-Type':'application/json','X-Social-OS-Workspace':workspace}:{})},...(data?{body:JSON.stringify(data)}:{})});const result=await response.json();if(!response.ok)throw Error(result.error||'Anfrage fehlgeschlagen');return result;}
function field(parent,label,value='',multi=false){const box=node('label',label);const input=document.createElement(multi?'textarea':'input');input.value=value;box.append(input);parent.append(box);return input;}
function action(parent,label,generation,callback){const button=node('button',label);button.type='button';button.onclick=async()=>{if(generation!==epoch)return;button.disabled=true;try{await callback();if(generation===epoch)await load();}catch(e){if(generation===epoch){$('message').textContent=e.message;button.disabled=false;}}};parent.append(button);}
function section(root,title){const area=document.createElement('section');area.append(node('h3',title));root.append(area);return area;}
async function load(){clear();const generation=epoch,ws=$('workspace').value;if(!ws)return;try{
 const path='/api/workspaces/'+ws;const snap=await api(path+'/snapshot');if(generation!==epoch)return;const root=$('content');
 root.append(node('h2',snap.brand.name),node('p',(snap.brand.provider==='instagram-standalone'?'Instagram Standalone':'Instagram')+' · '+snap.brand.integrationId,'muted'));
 const dna=section(root,'Brand DNA');const current=snap.dna||{};
 const audience=field(dna,'Zielgruppe',current.audience||'',true),voice=field(dna,'Sprache und Ton',current.voice||'',true),offer=field(dna,'Verifiziertes Angebot',current.offer||'',true),rules=field(dna,'Redaktionelle Regeln · eine pro Zeile',(current.rules||[]).join('\n'),true),evidence=field(dna,'Quellen und Nachweise',current.evidence||'',true);
 action(dna,'Brand DNA speichern',generation,()=>api(path+'/dna',{dna:{audience:audience.value,voice:voice.value,offer:offer.value,rules:rules.value.split('\n').map(s=>s.trim()).filter(Boolean),evidence:evidence.value},version:snap.dnaVersion},ws));
 const assets=section(root,'Medien dieser Marke');assets.append(node('p','Verwende bereits hochgeladene Postiz-Medien mit dauerhafter Adresse und dokumentierten Nutzungsrechten.','muted'));
 for(const asset of snap.assets)assets.append(node('p',asset.id+' · '+asset.evidence));
 const assetId=field(assets,'Postiz-Medien-ID'),assetPath=field(assets,'Dauerhafte HTTPS-Adresse'),assetEvidence=field(assets,'Quelle und Nutzungsrechte', '',true);
 action(assets,'Medium registrieren',generation,()=>api(path+'/assets',{asset:{id:assetId.value,path:assetPath.value},evidence:assetEvidence.value},ws));
 const compose=section(root,'Neuer Entwurf');const caption=field(compose,'Caption','',true);caption.maxLength=2200;
 const typeLabel=node('label','Format'),postType=document.createElement('select');for(const [value,label] of [['post','Feed / Reel'],['story','Story']]){const o=node('option',label);o.value=value;postType.append(o);}typeLabel.append(postType);compose.append(typeLabel);
 const selections=[];for(const asset of snap.assets){const l=node('label',asset.id),check=document.createElement('input');check.type='checkbox';l.prepend(check);compose.append(l);selections.push({asset,check});}
 if(!snap.assets.length)compose.append(node('p','Registriere zuerst ein Medium für diese Marke.','muted'));
 action(compose,'Entwurf zur Prüfung speichern',generation,()=>api(path+'/drafts',{payload:{caption:caption.value,postType:postType.value,media:selections.filter(s=>s.check.checked).map(s=>({id:s.asset.id,path:s.asset.path}))},dnaVersion:snap.dnaVersion},ws));
 const drafts=section(root,'Entwürfe und Freigaben');const labels={pending:'Zur Prüfung',approved:'Als Entwurf freigegeben',rejected:'Abgelehnt',exporting:'Export ungeklärt · keine Wiederholung',exported:'Postiz-Entwurf bestätigt'};
 if(!snap.drafts.length)drafts.append(node('p','Noch keine Entwürfe für diese Marke.'));
 for(const draft of snap.drafts){const card=document.createElement('article');card.append(node('p',draft.payload.caption,'caption'),node('p',labels[draft.status]+' · Revision '+draft.revision,'muted'));
 for(const m of draft.payload.media){const a=node('a','Medium '+m.id);a.href=m.path;a.target='_blank';a.rel='noopener noreferrer';card.append(a,node('br',''));}
 if(draft.dna_version!==snap.dnaVersion)card.append(node('p','Brand DNA wurde geändert. Erstelle einen neuen Entwurf.'));
 else for(const [name,label] of [['approve','Entwurf freigeben'],['reject','Ablehnen'],['export-draft','Als Postiz-Entwurf speichern']]){if((name==='export-draft'&&draft.status!=='approved')||(name!=='export-draft'&&draft.status!=='pending'))continue;action(card,label,generation,()=>api(path+'/drafts/'+draft.id+'/'+name,{revision:draft.revision},ws));}drafts.append(card);}
 const analytics=section(root,'Analytics');analytics.append(node('p','Letzte Erfassung: '+(snap.analyticsAt?new Date(snap.analyticsAt).toLocaleString():'noch keine'),'muted'));
 if(Array.isArray(snap.analytics))for(const metric of snap.analytics){analytics.append(node('h4',String(metric.label)));const table=document.createElement('table');for(const point of metric.data||[]){const row=document.createElement('tr');row.append(node('td',String(point.date)),node('td',String(point.total)));table.append(row);}analytics.append(table);}else analytics.append(node('p','Noch keine bestätigten Analytics verfügbar.'));
 const history=section(root,'Content-Historie');const events={'dna-updated':'Brand DNA aktualisiert','asset-registered':'Medium registriert','draft-created':'Entwurf erstellt',approved:'Entwurf freigegeben',rejected:'Entwurf abgelehnt','draft-export-claimed':'Entwurfsexport gestartet','provider-draft-verified':'Postiz-Entwurf bestätigt'};
 for(const e of snap.history)history.append(node('p',new Date(e.occurred_at).toLocaleString()+' · '+e.actor+' · '+(events[e.action]||e.action)+(e.draft_id?' · '+e.draft_id:''),'muted'));
 root.append(node('p','Kanalprüfung: '+(snap.providerOk?'bestätigt':'nicht bestätigt')+' · '+(snap.checkedAt?new Date(snap.checkedAt).toLocaleString():'ausstehend'),'muted'));
}catch(e){if(generation===epoch)$('message').textContent=e.message;}}
$('login').onclick=async()=>{clear();const generation=epoch;token=$('token').value;$('token').value='';try{const data=await api('/api/workspaces');if(generation!==epoch)return;$('workspace').replaceChildren();for(const w of data.workspaces){const o=node('option',w.name+' · '+(w.provider==='instagram-standalone'?'Instagram Standalone':'Instagram'));o.value=w.slug;$('workspace').append(o);}$('workspace').disabled=false;await load();}catch(e){if(generation===epoch)$('message').textContent=e.message;}};
$('logout').onclick=()=>{token='';$('token').value='';$('workspace').replaceChildren();$('workspace').disabled=true;clear();};$('workspace').onchange=load;
`;
